[workspace]
members = ["controller", "pingress-config", "proxy"]

[workspace.package]
edition = "2024"

[workspace.dependencies]
pingress-config = { path = "pingress-config" }
controller = { path = "controller" }
proxy-server = { path = "proxy" }

tokio = "1.49.0"
futures = "0.3.32"
async-trait = "0.1.89"

kube = "2.0.1"
k8s-openapi = "0.27.0"

pingora = "0.6.0"

clap = "4.5.55"

serde = "1.0.219"
serde_json = "1.0.149"

notify = "8.2.0"
nix = "0.31.1"

regex = "1.12.2"

log = "0.4.28"
env_logger = "0.11.8"

[package]
name = "pingress-controller"
edition.workspace = true

[[bin]]
name = "controller"
path = "src/controller/main.rs"
required-features = ["controller"]

[[bin]]
name = "proxy"
path = "src/proxy/main.rs"
required-features = ["proxy"]

[dependencies]
controller = { workspace = true, optional = true }
proxy-server = { workspace = true, optional = true }

tokio = { workspace = true, features = ["full"] }
clap = { workspace = true, features = ["derive"] }

log.workspace = true
env_logger.workspace = true

kube = { workspace = true, optional = true }

[features]
controller = ["dep:controller", "dep:kube"]
proxy = ["dep:proxy-server"]
