[package]
name = "proxy-server"
version = "0.1.0"
edition.workspace = true

[dependencies]
pingress-config.workspace = true

# pingora
pingora = { workspace = true, features = ["proxy", "boringssl"] }

# serde
serde_json.workspace = true

# logs
log.workspace = true

# async
async-trait.workspace = true
tokio = { workspace = true, features = ["full"] }

# misc
regex.workspace = true

# reload
notify.workspace = true
nix = { workspace = true, features = ["signal"] }
