apiVersion: v1
kind: Namespace
metadata:
  name: pingress-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingress-controller
  namespace: pingress-system
  labels:
    app.kubernetes.io/name: pingress-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: pingress-controller
  template:
    metadata:
      labels:
        app.kubernetes.io/name: pingress-controller
    spec:
      serviceAccountName: pingress-controller-user
      containers:
        - name: pingress-controller
          image: ghcr.io/kinorca/pingress-controller
          command: [ "/usr/local/bin/pingress-controller", "--backend=HostPort" ]
          env:
            - name: RUST_LOG
              value: debug
          imagePullPolicy: Always
